auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  chunk_idle_period: 1h
  chunk_block_size: 512MB
  max_chunk_age: 1h
  max_transfer_retries: 0
  byte_range_sync:
    enabled: true
  tsdb:
    retention_deletes_enabled: true
    retention_period: 7d

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 7d
